---
- name: Add Samba share to host storage
  hosts: all
  become: true
  
  tasks:
  - name: Install cifs-utils package
    ansible.builtin.package:
      name: cifs-utils
      state: latest
  - name: Create /mnt/data if it does not exist
    ansible.builtin.file:
      path: /mnt/data/
      state: directory
      mode: '0755'
  - name: Ensure secrets file exists
    stat: 
      path: /root/.smb-secrets
    register: secrets
  - name: Pause if secrets file does not exist
    pause:
      prompt: |
        "Put credentials into /root/.smb-secrets
        (user=username on first line, password=password on second) "
    when: not secrets.stat.exists
  - name: Secure secrets file permissions
    ansible.builtin.file:
      path: /root/.smb-secrets
      owner: root
      group: root
      mode: '0600'
  - name: Mount share to /mnt/data
    ansible.posix.mount:
      src: //nas.host/nas/
      path: /mnt/data
      opts: x-systemd.automount,credentials=/root/.smb-secrets,file_mode=0775,dir_mode=0775,uid=1000,gid=1000
      state: mounted
      fstype: cifs
  - name: Make sure drive mounts on boot
    ansible.builtin.systemd:
      name: systemd-networkd-wait-online
      state: started
      enabled: yes
