---
- name: Deploy Docker to Debian-based hosts
  hosts: all
  become: true
  
  tasks:
  - name: End if host is not Debian
    fail:
      msg: Host {{ inventory_hostname }} is not Debian, exiting...
    when: ansible_distribution != "Debian"
  - name: Install prerequisites for Docker
    apt:
      name: ['ca-certificates', 'curl', 'gnupg', 'lsb-release']
      state: latest
      update_cache: yes
  - name: Add Docker repository keys
    shell: >
      wget -O- https://download.docker.com/linux/debian/gpg
      | gpg --dearmor > /usr/share/keyrings/docker-archive-keyring.gpg
  - name: Add Docker repository to apt sources
    shell: >
      echo "deb [arch=$(dpkg --print-architecture)
      signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/debian
      $(lsb_release -cs) stable" 
      > /etc/apt/sources.list.d/docker.list
  - name: Install Docker packages
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'python3-pip', 'python3-setuptools', 'build-essential']
      state: latest
      update_cache: yes
  - name: Install docker-compose
    pip:
      name: docker-compose
      executable: pip3
  - name: Add rcunov to docker group
    ansible.builtin.user:
      name: rcunov
      groups: docker
      append: yes
